import 'package:flutter/material.dart';
import 'trip.dart';
import 'category.dart';

const Categories_data = const [
  Category(
    id: 'c1',
    title: "Mountains",
    imageUrl:
        'https://images.unsplash.com/photo-1575728252059-db43d03fc2de?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NTh8fG1vdW5hdGluc3xlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=',
  ),
  Category(
    id: 'c2',
    title: "Lakes",
    imageUrl:
        'https://images.unsplash.com/photo-1501785888041-af3ef285b470?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8bGFrZXxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60',
  ),
  Category(
    id: 'c3',
    title: "Beaches",
    imageUrl:
        'https://images.unsplash.com/photo-1493558103817-58b2924bce98?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTAxfHxiZWFjaHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60',
  ),
  Category(
    id: 'c4',
    title: "Deserts",
    imageUrl:
        'https://images.unsplash.com/photo-1473580044384-7ba9967e16a0?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MXx8ZGVzZXJ0fGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60',
  ),
  Category(
    id: 'c5',
    title: "Historic cities",
    imageUrl:
        'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NjR8fHRyYXZlbHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60',
  ),
  Category(
    id: 'c6',
    title: "Other",
    imageUrl:
        'https://images.unsplash.com/photo-1605540436563-5bca919ae766?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MXx8c2tpaW5nfGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60',
  ),
];
const Trips_data = [
  Trip(
    'm1',
    [
      'c1',
    ],
    "Alps",
    TripType.Exploration,
    Season.Winter,
    'https://images.unsplash.com/photo-1611523658822-385aa008324c?ixid=MXwxMjA3fDB8MHxzZWFyY2h8N3x8bW91bmF0aW5zfGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    20,
    [
      "Visit the main sites",
      "A walking tour",
      "Visiting malls for shopping",
      "Eat lunch",
      "Enjoy the beautiful scenery",
    ],
    [
      "Visit the main sites",
      "A walking tour",
      "Visiting malls for shopping",
      "Eat lunch",
      "Enjoy the beautiful scenery",
    ],
    false,
    true,
    true,
  ),
  Trip(
    'm2',
    [
      'c1',
    ],
    "Southern mountains",
    TripType.Exploration,
    Season.Winter,
    'https://images.unsplash.com/photo-1612456225451-bb8d10d0131d?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MjZ8fG1vdW5hdGluc3xlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    10,
    [
      "Visit the main sites",
      "A walking tour",
      "Visiting malls for shopping",
      "Eat lunch",
      "Enjoy the beautiful scenery",
    ],
    [
      "Visit the main sites",
      "A walking tour",
      "Visiting malls for shopping",
      "Eat lunch",
      "Enjoy the beautiful scenery",
    ],
    false,
    false,
    false,
  ),
  Trip(
    'm3',
    [
      'c1',
    ],
    "High mountains",
    TripType.Recovery,
    Season.Winter,
    'https://images.unsplash.com/photo-1592221912790-2b4df8882ea9?ixid=MXwxMjA3fDB8MHxzZWFyY2h8Mzd8fG1vdW5hdGluc3xlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    45,
    [
      "Visit the main sites",
      "A walking tour",
      "Visiting malls for shopping",
      "Eat lunch",
      "Enjoy the beautiful scenery",
    ],
    [
      "Visit the main sites",
      "A walking tour",
      "Visiting malls for shopping",
      "Eat lunch",
      "Enjoy the beautiful scenery",
    ],
    false,
    false,
    true,
  ),
  Trip(
    'm4',
    [
      'c2',
      'c1',
    ],
    "The Great Lake",
    TripType.Activities,
    Season.Spring,
    'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?ixid=MXwxMjA3fDB8MHxzZWFyY2h8OXx8bGFrZXxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    60,
    [
      "Visit the main sites",
      "A walking tour",
      "Visiting malls for shopping",
      "Eat lunch",
      "Enjoy the beautiful scenery",
    ],
    [
      "Visit the main sites",
      "A walking tour",
      "Visiting malls for shopping",
      "Eat lunch",
      "Enjoy the beautiful scenery",
    ],
    false,
    false,
    false,
  ),
  Trip(
    'm5',
    [
      'c2',
      'c1',
    ],
    "Minor lakes",
    TripType.Activities,
    Season.Winter,
    'https://images.unsplash.com/photo-1580100586938-02822d99c4a8?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MjF8fGxha2V8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=600&q=60',
    15,
    [
      "Visit the main sites",
      "A walking tour",
      "Visiting malls for shopping",
      "Eat lunch",
      "Enjoy the beautiful scenery",
    ],
    [
      "Visit the main sites",
      "A walking tour",
      "Visiting malls for shopping",
      "Eat lunch",
      "Enjoy the beautiful scenery",
    ],
    true,
    false,
    true,
  ),
  Trip(
    'm6',
    [
      'c2',
    ],
    "Emerald Lake",
    TripType.Exploration,
    Season.Summer,
    'https://images.unsplash.com/photo-1501785888041-af3ef285b470?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8bGFrZXxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=600&q=60',
    240,
    [
      "Visit the main sites",
      "A walking tour",
      "Visiting malls for shopping",
      "Eat lunch",
      "Enjoy the beautiful scenery",
    ],
    [
      "Visit the main sites",
      "A walking tour",
      "Visiting malls for shopping",
      "Eat lunch",
      "Enjoy the beautiful scenery",
    ],
    true,
    false,
    false,
  ),
  Trip(
    'm7',
    [
      'c3',
    ],
    "The first beach",
    TripType.Exploration,
    Season.Winter,
    'https://images.unsplash.com/photo-1493558103817-58b2924bce98?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTAxfHxiZWFjaHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=600&q=60',
    20,
    [
      "Visit the main sites",
      "A walking tour",
      "Visiting malls for shopping",
      "Eat lunch",
      "Enjoy the beautiful scenery",
    ],
    [
      "Visit the main sites",
      "A walking tour",
      "Visiting malls for shopping",
      "Eat lunch",
      "Enjoy the beautiful scenery",
    ],
    true,
    false,
    false,
  ),
  Trip(
    'm8',
    [
      'c3',
    ],
    "The big beach",
    TripType.Recovery,
    Season.Spring,
    'https://images.unsplash.com/photo-1519046904884-53103b34b206?ixid=MXwxMjA3fDB8MHxzZWFyY2h8Mnx8YmVhY2h8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    35,
    [
      "Visit the main sites",
      "A walking tour",
      "Visiting malls for shopping",
      "Eat lunch",
      "Enjoy the beautiful scenery",
    ],
    [
      "Visit the main sites",
      "A walking tour",
      "Visiting malls for shopping",
      "Eat lunch",
      "Enjoy the beautiful scenery",
    ],
    true,
    false,
    true,
  ),
  Trip(
    'm9',
    [
      'c3',
    ],
    "rock beach",
    TripType.Exploration,
    Season.Summer,
    'https://images.unsplash.com/photo-1519602035691-16ac091344ef?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MjE1fHxiZWFjaHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=600&q=60',
    45,
    [
      "Visit the main sites",
      "A walking tour",
      "Visiting malls for shopping",
      "Eat lunch",
      "Enjoy the beautiful scenery",
    ],
    [
      "Visit the main sites",
      "A walking tour",
      "Visiting malls for shopping",
      "Eat lunch",
      "Enjoy the beautiful scenery",
    ],
    true,
    false,
    false,
  ),
  Trip(
    'm10',
    [
      'c4',
    ],
    "The Great Desert",
    TripType.Activities,
    Season.Winter,
    'https://images.unsplash.com/photo-1473580044384-7ba9967e16a0?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MXx8ZGVzZXJ0fGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    30,
    [
      "Visit the main sites",
      "A walking tour",
      "Visiting malls for shopping",
      "Eat lunch",
      "Enjoy the beautiful scenery",
    ],
    [
      "Visit the main sites",
      "A walking tour",
      "Visiting malls for shopping",
      "Eat lunch",
      "Enjoy the beautiful scenery",
    ],
    true,
    true,
    true,
  ),
  Trip(
    'm11',
    [
      'c4',
      'c1',
    ],
    "Western Desert",
    TripType.Activities,
    Season.Winter,
    'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=600&q=60',
    30,
    [
      "Visit the main sites",
      "A walking tour",
      "Visiting malls for shopping",
      "Eat lunch",
      "Enjoy the beautiful scenery",
    ],
    [
      "Visit the main sites",
      "A walking tour",
      "Visiting malls for shopping",
      "Eat lunch",
      "Enjoy the beautiful scenery",
    ],
    true,
    true,
    true,
  ),
  Trip(
    'm12',
    [
      'c4',
    ],
    "Sandy desert",
    TripType.Activities,
    Season.Winter,
    'https://images.unsplash.com/photo-1452022582947-b521d8779ab6?ixid=MXwxMjA3fDB8MHxzZWFyY2h8ODN8fGRlc2VydHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=600&q=60',
    30,
    [
      "Visit the main sites",
      "A walking tour",
      "Visiting malls for shopping",
      "Eat lunch",
      "Enjoy the beautiful scenery",
    ],
    [
      "Visit the main sites",
      "A walking tour",
      "Visiting malls for shopping",
      "Eat lunch",
      "Enjoy the beautiful scenery",
    ],
    true,
    true,
    true,
  ),
  Trip(
    'm13',
    [
      'c5',
    ],
    "The first city",
    TripType.Activities,
    Season.Winter,
    'https://images.unsplash.com/photo-1498307833015-e7b400441eb8?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NDJ8fHRyYXZlbHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=600&q=60',
    30,
    [
      "Visit the main sites",
      "A walking tour",
      "Visiting malls for shopping",
      "Eat lunch",
      "Enjoy the beautiful scenery",
    ],
    [
      "Visit the main sites",
      "A walking tour",
      "Visiting malls for shopping",
      "Eat lunch",
      "Enjoy the beautiful scenery",
    ],
    true,
    true,
    true,
  ),
  Trip(
    'm14',
    [
      'c5',
    ],
    "The second city",
    TripType.Activities,
    Season.Winter,
    'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NjR8fHRyYXZlbHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=600&q=60',
    30,
    [
      "Visit the main sites",
      "A walking tour",
      "Visiting malls for shopping",
      "Eat lunch",
      "Enjoy the beautiful scenery",
    ],
    [
      "Visit the main sites",
      "A walking tour",
      "Visiting malls for shopping",
      "Eat lunch",
      "Enjoy the beautiful scenery",
    ],
    true,
    true,
    true,
  ),
  Trip(
    'm15',
    [
      'c5',
    ],
    "old City",
    TripType.Activities,
    Season.Winter,
    'https://images.unsplash.com/photo-1519923041107-e4dc8d9193da?ixid=MXwxMjA3fDB8MHxzZWFyY2h8Njd8fG9sZCUyMGNpdHl8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=600&q=60',
    30,
    [
      "Visit the main sites",
      "A walking tour",
      "Visiting malls for shopping",
      "Eat lunch",
      "Enjoy the beautiful scenery",
    ],
    [
      "Visit the main sites",
      "A walking tour",
      "Visiting malls for shopping",
      "Eat lunch",
      "Enjoy the beautiful scenery",
    ],
    true,
    true,
    true,
  ),
  Trip(
    'm16',
    [
      'c6',
    ],
    "Snow sports",
    TripType.Activities,
    Season.Winter,
    'https://images.unsplash.com/photo-1605540436563-5bca919ae766?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MXx8c2tpaW5nfGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=600&q=60',
    30,
    [
      "Visit the main sites",
      "A walking tour",
      "Visiting malls for shopping",
      "Eat lunch",
      "Enjoy the beautiful scenery",
    ],
    [
      "Visit the main sites",
      "A walking tour",
      "Visiting malls for shopping",
      "Eat lunch",
      "Enjoy the beautiful scenery",
    ],
    true,
    true,
    true,
  ),
  Trip(
    'm17',
    [
      'c6',
      'c2',
    ],
    "jet skiting",
    TripType.Activities,
    Season.Winter,
    'https://images.unsplash.com/photo-1601024445121-e5b82f020549?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTJ8fHBhcmFjaHV0ZSUyMGp1bXBpbmd8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=600&q=60',
    30,
    [
      "Visit the main sites",
      "A walking tour",
      "Visiting malls for shopping",
      "Eat lunch",
      "Enjoy the beautiful scenery",
    ],
    [
      "Visit the main sites",
      "A walking tour",
      "Visiting malls for shopping",
      "Eat lunch",
      "Enjoy the beautiful scenery",
    ],
    true,
    true,
    true,
  ),
];
